from pathlib import Path
import csv

import cv2
import numpy as np
import streamlit as st
from PIL import Image
from streamlit_drawable_canvas import st_canvas


# ----------------------------
# Configuration
# ----------------------------
CALIBRATION_FILE = Path("calibration.npz")
CSV_FILE = Path("measurements.csv")

CSV_COLUMNS = [
    "object_name",
    "camera_distance_m",
    "pixel_width",
    "pixel_height",
    "estimated_width_cm",
    "estimated_height_cm",
    "actual_width_cm",
    "actual_height_cm",
    "width_error_cm",
    "height_error_cm",
]


def blank_value():
    return ""


def read_measurements():
    if not CSV_FILE.exists() or CSV_FILE.stat().st_size == 0:
        return []

    with CSV_FILE.open("r", newline="", encoding="utf-8") as csv_file:
        reader = csv.DictReader(csv_file)
        return [
            {column: row.get(column, "") for column in CSV_COLUMNS}
            for row in reader
        ]


def write_measurements(records):
    with CSV_FILE.open("w", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=CSV_COLUMNS)
        writer.writeheader()
        writer.writerows(records)


def to_float(value):
    try:
        if value in ("", None):
            return None
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if np.isfinite(number) else None


def numeric_pairs(records, actual_column, estimated_column):
    pairs = []
    for record in records:
        actual = to_float(record.get(actual_column))
        estimated = to_float(record.get(estimated_column))
        if actual is not None and actual > 0 and estimated is not None:
            pairs.append((actual, estimated))
    return pairs


def markdown_table(records):
    def clean(value):
        text = "" if value is None else str(value)
        return text.replace("|", "\\|").replace("\n", " ")

    header = "| " + " | ".join(CSV_COLUMNS) + " |"
    separator = "| " + " | ".join(["---"] * len(CSV_COLUMNS)) + " |"
    rows = [
        "| "
        + " | ".join(clean(record.get(column, "")) for column in CSV_COLUMNS)
        + " |"
        for record in records
    ]
    return "\n".join([header, separator, *rows])

st.set_page_config(
    page_title="Camera Measurement Tool",
    page_icon="📏",
    layout="wide",
)

st.title("Camera-Based Object Measurement")
st.write(
    "Upload an image, draw a rectangle around the object, and enter the "
    "camera distance. The app estimates the object's real-world dimensions."
)


# ----------------------------
# Load calibration
# ----------------------------
@st.cache_resource
def load_calibration(path_string):
    with np.load(path_string) as calibration:
        camera_matrix = calibration["camera_matrix"]
        dist_coeffs = calibration["dist_coeffs"]
        rms_error = float(calibration["rms_error"])

    return camera_matrix, dist_coeffs, rms_error


if not CALIBRATION_FILE.exists():
    st.error(
        "calibration.npz was not found. Run `python calibrate.py` first."
    )
    st.stop()

try:
    camera_matrix, dist_coeffs, rms_error = load_calibration(
        str(CALIBRATION_FILE)
    )
except (KeyError, OSError, ValueError) as error:
    st.error(
        "Could not read calibration.npz. Make sure it was generated by "
        f"the updated calibrate.py. Details: {error}"
    )
    st.stop()

fx = float(camera_matrix[0, 0])
fy = float(camera_matrix[1, 1])

if fx <= 0 or fy <= 0:
    st.error("Calibration contains invalid focal lengths.")
    st.stop()

st.success("Camera calibration loaded.")
st.caption(f"Calibration RMS error: {rms_error:.4f} pixels")


# ----------------------------
# Upload image
# ----------------------------
uploaded_file = st.file_uploader(
    "Upload an object image",
    type=["jpg", "jpeg", "png"],
)

if uploaded_file is None:
    st.info("Upload an image to start.")
    st.stop()

image_bytes = np.frombuffer(uploaded_file.getvalue(), dtype=np.uint8)
image = cv2.imdecode(image_bytes, cv2.IMREAD_COLOR)

if image is None:
    st.error("The uploaded file could not be read.")
    st.stop()

original_height, original_width = image.shape[:2]

undistorted = cv2.undistort(image, camera_matrix, dist_coeffs)
undistorted_rgb = cv2.cvtColor(undistorted, cv2.COLOR_BGR2RGB)

st.subheader("Draw a rectangle around your object")
st.write(
    "Click and drag from one corner of the object to the opposite corner. "
    "Try to include the object's full width and height, but not extra "
    "background."
)

# Display at a manageable size while preserving the original aspect ratio.
MAX_CANVAS_WIDTH = 750
display_scale = min(1.0, MAX_CANVAS_WIDTH / original_width)

canvas_width = max(1, int(round(original_width * display_scale)))
canvas_height = max(1, int(round(original_height * display_scale)))

display_image = Image.fromarray(undistorted_rgb).resize(
    (canvas_width, canvas_height)
)

canvas_result = st_canvas(
    fill_color="rgba(0, 150, 255, 0.15)",
    stroke_width=2,
    stroke_color="#0096FF",
    background_image=display_image,
    update_streamlit=True,
    height=canvas_height,
    width=canvas_width,
    drawing_mode="rect",
    key=f"object_canvas_{uploaded_file.name}_{original_width}_{original_height}",
)

st.caption(
    f"Original image resolution: {original_width} × {original_height} pixels. "
    "Draw on the undistorted image above."
)


# ----------------------------
# Get selected rectangle
# ----------------------------
pixel_width = None
pixel_height = None

canvas_data = canvas_result.json_data

if canvas_data and canvas_data.get("objects"):
    # Use the most recently drawn rectangle.
    rectangle = canvas_data["objects"][-1]

    left = float(rectangle.get("left", 0))
    top = float(rectangle.get("top", 0))
    rect_width = float(rectangle.get("width", 0))
    rect_height = float(rectangle.get("height", 0))

    # Fabric canvas objects may include scaleX/scaleY.
    rect_width *= float(rectangle.get("scaleX", 1))
    rect_height *= float(rectangle.get("scaleY", 1))

    # Convert displayed-canvas coordinates to original-image pixels.
    scale_x = original_width / canvas_width
    scale_y = original_height / canvas_height

    pixel_width = int(round(rect_width * scale_x))
    pixel_height = int(round(rect_height * scale_y))

    if pixel_width > 0 and pixel_height > 0:
        st.info(
            f"Selected object: **{pixel_width} px wide × "
            f"{pixel_height} px high**"
        )
    else:
        pixel_width = None
        pixel_height = None

if pixel_width is None or pixel_height is None:
    st.warning("Draw a rectangle around the object to calculate its pixel size.")


# ----------------------------
# Measurement inputs
# ----------------------------
st.subheader("Measurement details")

with st.form("measurement_form"):
    object_name = st.text_input(
        "Object name or ID",
        placeholder="Example: Object 1",
    )

    distance_m = st.number_input(
        "Camera-to-object distance (meters)",
        min_value=0.01,
        value=2.5,
        step=0.1,
    )

    actual_width_cm = st.number_input(
        "Actual width in cm (enter 0 if unknown)",
        min_value=0.0,
        value=0.0,
        step=0.1,
    )

    actual_height_cm = st.number_input(
        "Actual height in cm (enter 0 if unknown)",
        min_value=0.0,
        value=0.0,
        step=0.1,
    )

    save_measurement = st.form_submit_button(
        "Calculate and save measurement",
        disabled=(pixel_width is None or pixel_height is None),
    )


# ----------------------------
# Calculate and save
# ----------------------------
if save_measurement:
    if not object_name.strip():
        st.error("Enter an object name or ID.")
    elif pixel_width is None or pixel_height is None:
        st.error("Draw a rectangle around the object first.")
    else:
        # Pinhole-camera approximation.
        # fx and fy are in pixels; distance is converted from meters to cm.
        estimated_width_cm = pixel_width * distance_m * 100.0 / fx
        estimated_height_cm = pixel_height * distance_m * 100.0 / fy

        width_error_cm = (
            estimated_width_cm - actual_width_cm
            if actual_width_cm > 0
            else blank_value()
        )
        height_error_cm = (
            estimated_height_cm - actual_height_cm
            if actual_height_cm > 0
            else blank_value()
        )

        new_row = {
            "object_name": object_name.strip(),
            "camera_distance_m": distance_m,
            "pixel_width": pixel_width,
            "pixel_height": pixel_height,
            "estimated_width_cm": estimated_width_cm,
            "estimated_height_cm": estimated_height_cm,
            "actual_width_cm": (
                actual_width_cm if actual_width_cm > 0 else blank_value()
            ),
            "actual_height_cm": (
                actual_height_cm if actual_height_cm > 0 else blank_value()
            ),
            "width_error_cm": width_error_cm,
            "height_error_cm": height_error_cm,
        }

        try:
            records = read_measurements()
            records.append(new_row)
            write_measurements(records)

            st.success("Measurement calculated and saved.")

            col1, col2 = st.columns(2)
            col1.metric("Estimated width", f"{estimated_width_cm:.2f} cm")
            col2.metric("Estimated height", f"{estimated_height_cm:.2f} cm")

            st.caption(
                "This estimate assumes the object is approximately front-facing "
                "and at the distance you entered."
            )

        except OSError as error:
            st.error(f"Could not save measurements.csv: {error}")


# ----------------------------
# Show saved measurements
# ----------------------------
st.divider()
st.subheader("Saved measurements")

records = read_measurements()

if not records:
    st.info("No measurements saved yet.")
else:
    st.markdown(markdown_table(records))

    width_pairs = numeric_pairs(
        records,
        "actual_width_cm",
        "estimated_width_cm",
    )
    height_pairs = numeric_pairs(
        records,
        "actual_height_cm",
        "estimated_height_cm",
    )

    st.subheader("Validation error statistics")

    width_col, height_col = st.columns(2)

    with width_col:
        st.markdown("**Width**")

        if width_pairs:
            actual = np.array([pair[0] for pair in width_pairs])
            estimated = np.array([pair[1] for pair in width_pairs])
            errors = estimated - actual
            abs_errors = np.abs(errors)

            st.write(f"Measurements: {len(errors)}")
            st.write(f"MAE: {abs_errors.mean():.3f} cm")
            st.write(f"RMSE: {np.sqrt((errors ** 2).mean()):.3f} cm")
            st.write(f"MAPE: {(abs_errors / actual * 100).mean():.2f}%")
            st.write(f"Bias: {errors.mean():.3f} cm")
            st.write(f"Maximum absolute error: {abs_errors.max():.3f} cm")
        else:
            st.info("Enter actual widths to calculate width errors.")

    with height_col:
        st.markdown("**Height**")

        if height_pairs:
            actual = np.array([pair[0] for pair in height_pairs])
            estimated = np.array([pair[1] for pair in height_pairs])
            errors = estimated - actual
            abs_errors = np.abs(errors)

            st.write(f"Measurements: {len(errors)}")
            st.write(f"MAE: {abs_errors.mean():.3f} cm")
            st.write(f"RMSE: {np.sqrt((errors ** 2).mean()):.3f} cm")
            st.write(f"MAPE: {(abs_errors / actual * 100).mean():.2f}%")
            st.write(f"Bias: {errors.mean():.3f} cm")
            st.write(f"Maximum absolute error: {abs_errors.max():.3f} cm")
        else:
            st.info("Enter actual heights to calculate height errors.")

    st.download_button(
        "Download measurements.csv",
        data=CSV_FILE.read_bytes(),
        file_name="measurements.csv",
        mime="text/csv",
    )
